### ISSUE TITLE
Is the tiny-cuda-nn updated?

### ISSUE THREAD

**Issue by h8c2** [hturki/suds#1]
Amazing Work!
After reading your paper carefully, I was very interested in the implementing of your own hash grid.
However, I found the _git+https://github.com/hturki/tiny-cuda-nn.git@ht/res-grid#subdirectory=bindings/torch_ was an empty folder.
And the codes in _https://github.com/hturki/tiny-cuda-nn_ seems to be the same implementation as the original.
I was wondering if I didn't do it the right way or if the source code hasn't been uploaded yet.
I appreciate it if you give me some advice.
Thanks again for a great job of open source.

**Comment by h8c2** [comment]
Sorry for my stupid mistake.  I found the right branch.

**Comment by rockywind** [comment]
Hi, @h8c2 
How to build the tiny-cuda-nn.
This is my building error is [that](https://github.com/hturki/suds/issues/6).

**Comment by tb2-sy** [comment]
> Sorry for my stupid mistake. I found the right branch.

Hello, which one is the right branch? I have encountered the same problem and have not solved it yet,thank you.

**Comment by h8c2** [comment]
> 

![image](https://user-images.githubusercontent.com/37017782/230618254-6ef6b180-100d-4886-87e2-895b7f671005.png)

**Comment by tb2-sy** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/37017782/230618254-6ef6b180-100d-4886-87e2-895b7f671005.png)

Apologies for my stupid question and thanks for the patience to reply.
