### ISSUE TITLE
Do you consider add nuscenes support?

### ISSUE THREAD

**Issue by synsin0** [hturki/suds#10]
Thanks for your great work. I see in your modified nerfstudio you add the nuscenes dataset parser support. May you provide some guidance on how to implement nerf on nuscenes dataset?

**Comment by fferroni** [comment]
You can try running this script in the nuscenes devkit (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py) which exports the nuscenes dataset into KITTI format, then you wouldn't need to write any new parser. The script however should contain all the necessary functions to adapt the data.

**Comment by synsin0** [comment]
Get it! We will try suds on nuScenes / Waymo dataset! Thanks again!
