### ISSUE TITLE
How to deal with kitti odom?

### ISSUE THREAD

**Issue by AIBUWAN** [hturki/suds#12]
I want to deal with dataset KITTI odom,which  calib.txt has P0,P1,P2,p3,Tr，not have R_rect and  Tr_velo_cam.

but there need R_rect and  Tr_velo_cam[https://github.com/hturki/suds/blame/main/scripts/create_kitti_depth_maps.py#L38](url),

Please help me! thanks!

**Comment by hturki** [comment]
I've only tested this out with the KITTI MOT dataset - you'll likely need to modify the script to take the odometry file format into account.
