### ISSUE TITLE
How to generate the .json files in the metadata folder?

### ISSUE THREAD

**Issue by FollowingWind117** [hturki/suds#14]
Hi, Thank you for sharing the code.
I notice that there is only a "kitti-06.json" in metadata folder.If i want to use other kitti sequences like 0005 or 0004, how can i generate the json files like "kitti-06.json"?
Thank you in advance for your response!

**Comment by AIBUWAN** [comment]
Maybe you can use `python scripts/create_kitti_metadata.py --config_file scripts/configs/$CONFIG_FILE` by modifing CONFIG_FILE

**Comment by hturki** [comment]
this is correct

**Comment by FollowingWind117** [comment]
> Maybe you can use `python scripts/create_kitti_metadata.py --config_file scripts/configs/$CONFIG_FILE` by modifing CONFIG_FILE

Thank you very much. I know how to solve this problem.
