### ISSUE TITLE
“No module named 'suds'”

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#2]
Hi, thank you for sharing the great work!
I met the error below when I run the script `python scripts/create_kitti_depth_maps_my.py --kitti_sequence 0000`
![image](https://user-images.githubusercontent.com/14838781/229265846-f43b508b-9e26-4ffd-bd24-111bd56d53cc.png)

**Comment by hturki** [comment]
can you try setting your PYTHONPATH environment to the suds directory?
