### ISSUE TITLE
How to get the world-scale depth

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#22]
Hi,
Thank you for sharing the great work.
I found the depth map value is no the world-scale.
How can I get the world-scale value.
![image](https://user-images.githubusercontent.com/14838781/233276233-e6b338b2-ec16-498a-815e-84a8b4076e61.png)

![image](https://user-images.githubusercontent.com/14838781/233276390-1c8dbcca-2fa0-4fe3-926a-6727f0afd27c.png)

**Comment by hturki** [comment]
if you're using our metadata files, check the "pose_scale_factor" parameter

**Comment by rockywind** [comment]
Hi, Thank you for your help.
I found the value of `pose_scale_factor` is `87.76204257199016`.
If I want to get the world-scale depth value, I should multiply the value of `pose_scale_factor`.
![image](https://user-images.githubusercontent.com/14838781/233366648-3f55e9a3-3b34-4b95-b40a-aee51551aa4a.png)

**Comment by hturki** [comment]
that is correct
