### ISSUE TITLE
scripts/run_pca.py uses excessive memory

### ISSUE THREAD

**Issue by dllu** [hturki/suds#26]
It runs out of memory on a machine with 360 GB of ram.

I guess we can solve it by avoiding loading all the descriptors into memory. We can load a subset of it, fit the PCA on the subset, and then apply the transformation to the remaining data.

**Comment by hturki** [comment]
That would work. Another option which I used for the City1M dataset is to use Incremental PCA (https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.IncrementalPCA.html) with some batch size that fits in memory. Happy to accept PRs!
