### ISSUE TITLE
Potentially redundant for-loop in extract_dino_correspondences.py

### ISSUE THREAD

**Issue by dllu** [hturki/suds#27]
I see the following code:

https://github.com/hturki/suds/blob/main/scripts/extract_dino_correspondences.py#L96

```python
    for k in range(n_clusters):
        for i, (label, rank) in enumerate(zip(kmeans.labels_, ranks)):
            if rank > bb_topk_sims[label]:
                bb_topk_sims[label] = rank
                bb_indices_to_show[label] = i
```

I don't understand the outermost for-loop. It doesn't seem to affect any computation.

Moreover, I find that this loop is taking up 80% of the total run time (another 15% is taken up by k means, so overall the GPU utilization is quite poor).

![image (52)](https://github.com/hturki/suds/assets/14482624/8a06149c-cf97-4cc4-b119-a91ae52ce864)

**Comment by fferroni** [comment]
you are correct. nice catch, probably a mistake from refactoring into using sklearn's `kmeans.labels_`
