### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by Quantum-matrix** [hturki/suds#3]
Thanks for your great work.
Could you share your own default conda channels? I have trouble in installing the satisfied version.

**Comment by hturki** [comment]
I pushed a commit a few hours ago that removed a spurious entry (https://github.com/hturki/suds/commit/4ab59cd2d5cc7192d03fb020544fe264ecf92040) - are you still running into issues after that commit?

**Comment by Quantum-matrix** [comment]
Yes, I use your latest code.

**Comment by hturki** [comment]
could you share your error trace? I just tried out the latest commit on a fresh machine, and it seemed to install properly

**Comment by Quantum-matrix** [comment]
**_ERROR: Could not find a version that satisfies the requirement comm==0.1.3 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2)
ERROR: No matching distribution found for comm==0.1.3_**  
And there are quite a lot of modules like this.

**Comment by hturki** [comment]
what OS architecture are you using? I've mainly tested this out on CentOS 7, but this also worked on a fresh Ubuntu 20 install. I'm not using any custom channels or anything - I literally just spun up a fresh Ubuntu 20 instance in the cloud and things installed as expected.

**Comment by tb2-sy** [comment]
> **_ERROR: Could not find a version that satisfies the requirement comm==0.1.3 (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2) ERROR: No matching distribution found for comm==0.1.3_** And there are quite a lot of modules like this.

Hi, I have the same problem, did you solve it?

**Comment by Quantum-matrix** [comment]
@hturki Sorry for the late reply, it seems the default channel in China doesn't contain the latest version of modules. I've solved this problem by changing the default channel.  Thanks for your great work which helped me a lot.   @tb2-sy Maybe you're also in China mainland and I suggest you use the official channel: https://pypi.org/simple.

**Comment by fferroni** [comment]
@Quantum-matrix great that you solved it. if this works for you, then you can close the issue?

**Comment by Quantum-matrix** [comment]
@tb2-sy I noticed that you're also working on reproducing the result. Can we get in touch with WeChat?
