### ISSUE TITLE
Why the depth loss flucture so much?

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#30]
Hi, thank you for you sharing the great work.
I have a question that why the depth loss flucture so much?
The loss log is below.
![image](https://github.com/hturki/suds/assets/14838781/e31a0089-3364-423e-9947-44b4bfc207da)
![image](https://github.com/hturki/suds/assets/14838781/11732297-d001-4410-8dbd-07de1bf65ab6)

**Comment by hturki** [comment]
the depth points from lidar can be quite sparse. Our L1 depth loss is pretty simple - perhaps other methods can offer a smoother descent (there are some additional terms in https://urban-radiance-fields.github.io/ that I played around with, but didn't include in the paper / code release).

**Comment by rockywind** [comment]
thanks a lot!
