### ISSUE TITLE
Baselines

### ISSUE THREAD

**Issue by samiragarwala** [hturki/suds#35]
Thank you for the great work! I was trying to reproduce some of the baselines on Virtual Kitti and was wondering why the [ground plane Z transformation](https://github.com/hturki/suds/blob/9b472ad5e4fd4d810682af984ef65bfaf4d75188/scripts/create_vkitti2_metadata.py#L71) is necessary since the poses have been transformed to the OpenGL system?

If I understand correctly, except finding scene bounds based on the depth maps and rescaling the scene, is there any other processing applied to the data or important configuration to keep in mind before training the baselines?

Thank you!

**Comment by hturki** [comment]
The ground plane Z transformation is used so that altitude corresponds to the last position dimension (which is used in https://github.com/hturki/suds/blob/main/suds/suds_collider.py#L67). Otherwise if I recall correctly Virtual KITTI represents world coordinates as [down, right, backwards]

**Comment by samiragarwala** [comment]
Thank you for the clarification!
