### ISSUE TITLE
How to set the "FEATURE_CLUSTERS" in the training script?

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#4]
Hi, 
Thank you for sharing the great work!
I want to known how to set the `FEATURE_CLUSTERS` in the training script.
The below is my script.
````
python suds/train.py suds --experiment-name kitti_06 --pipeline.datamanager.dataparser.metadata_path metadata/kitti-06.json [--pipeline.feature_clusters $FEATURE_CLUSTERS]

````

**Comment by hturki** [comment]
you can set that optional parameter if you want to visualize the distilled DINO features. If so, follow the sections in the readme called "Generate feature clusters for visualization." This parameter is optional though.

**Comment by rockywind** [comment]
Thank you very much!

**Comment by AIBUWAN** [comment]
@rockywind @hturki 
I use this `python suds/train.py suds --experiment-name kitti_06 --pipeline.datamanager.dataparser.metadata_path metadata/kitti-06.json`,but  it  has problem.

 File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '/home/cc/suds/data/kitti/dino_02/0006/000000.parquet': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
python-BaseException

**Comment by hturki** [comment]
It looks like your parquet file wasn't written properly. You can try directly opening it in pyarrow to confirm.

**Comment by rockywind** [comment]
I run this directly `python suds/train.py suds --experiment-name kitti_06 --pipeline.datamanager.dataparser.metadata_path metadata/kitti-06.json `
