### ISSUE TITLE
Compute correspondence too slow!

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#9]
Thanks for your open-source of a complete urban-scale nerf! 
I attempt to preprocess this step to compute correspondence with DINO. For kitti-0006 sequence, it expects to task 1day more to get dino_correspondence with a single A6000 GPU. Is that normal? When you extend the images to thousands, the time is not bearable.

**Comment by fferroni** [comment]
Can you provide the command you used? Also, just sanity checking - is your GPU showing good utilisation?

**Comment by tb2-sy** [comment]
> For context, the correspondence extracting code is pretty slow - as mentioned in the paper we had to use RAFT for the City-1M experiments. But empirically DINO correspondences gave better results than RAFT. The existing extraction logic is mainly lifted from https://github.com/ShirAmir/dino-vit-features and can almost certainly be made faster for our purposes (very happy to accept PRs that would do so)

Hi,does Compute correspondence require a lot of memory? I am using a 48G A40, but it still shows that it exceeds out of memory. Is this normal? Is there any good solution? Thanks.

**Comment by hturki** [comment]
Reducing the load_size parameter should reduce your memory requirements

**Comment by tb2-sy** [comment]
> Reducing the load_size parameter should reduce your memory requirements

Thanks for your reply, but will changing this parameter have any bad effect on the subsequent process?

**Comment by hturki** [comment]
> > Reducing the load_size parameter should reduce your memory requirements
> 
> Thanks for your reply, but will changing this parameter have any bad effect on the subsequent process?

That parameter controls how much the images are downsampled before being passed into the DINO feature extractor. I suspect that our defaults are likely overkill (I mainly tried to use the maximum that would roughly fit into a A100 or A6000), but I haven't played around with this too much.

**Comment by Quantum-matrix** [comment]
Hello, so are there any ways to improve the speed? It seems it needs almost a month for DINO  preprocess on A100 which is unbearable.
